### ISSUE TITLE
article number

### ISSUE THREAD

**Issue by kkrebs** [MyCoRe-Org/pica2mods#16]
im Katalogisierungsschema des K10+ gibt es jetzt ein Subfeld zur Verzeichnung von Artikel IDs:
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4070&katalog=Standard#$i

Liegt bei einer elektronischen Ressource eine Artikelzählung anstelle einer durchgehenden Seitenzählung vor, wird die Artikel-ID in Unterfeld $i erfasst.

Wir müssen also nur noch entscheiden, wo wir die Artikel-ID im MODS ablegen. Idee wäre, das als Teil von mods:part abzulegen:
```
<detail type=“articlenumber">
  <number>99</number>
</detail>
```

**Comment by rsteph-de** [comment]
Hier
https://wiki.duraspace.org/download/attachments/87460857/MODS-RDF-Mapping-Recommendations_SMIG_v1_2019-01.pdf?version=3&modificationDate=1549383163287&api=v2

findet man das:
<mods:identifier type="article number">e0177396</mods:identifier>

**Comment by kkrebs** [comment]
Hier mal zwei Beispieldatensätze:
PPN 175090778X
PPN 1745828389

**Comment by kkrebs** [comment]
Auch wenn es sicher keine gute Vorlage ist, nur mal der Vollständigkeit halber wie es im MODS über die unapi kommt:
```
<part>
  <text>15(2021), Artikel-ID 552666$d9$m3</text>
</part>
```
bzw.
```
<part>
  <text>elocationid:552666$d9$m3</text>
</part>
```

Tatsächlich finde ich mods:identifier nicht so gut. Aber das ist wohl eher ein Bauchgefühl.

**Comment by kkrebs** [comment]
Nach Rücksprache auch mit Jena/Ilmenau sind wir uns einig, dass die Artikel-Nummer keine ID in dem Sinne ist, sondern ein Seitenersatz. Daher soll diese auch analog genutzt werden:

```
<detail type="article_number">
  <number>99</number>
</detail>
```
