### ISSUE TITLE
Keywords/topics from 045R, 044K and 044N

### ISSUE THREAD

**Issue by Possommi** [MyCoRe-Org/pica2mods#67]
Der Import von Schlagwörtern erfolgt nur eingeschränkt.

Das PICA+ Feld 045R für die RVK Notationen wird nicht importiert; ebenso wie das PICA+ Feld 044N $Ss für freie Schlagwörter.

Aus den PICA+ Feldern 044K/01 und 004K/02 wurden nicht alle im CBS enthaltenen Schlagwörter importiert.

Außerdem wurde ein als Schlagwort verwendeter Personenname unvollständig (nur der Nachname) importiert, siehe Screenshot.

Beispiele
PPN:1602014973
https://thunibib-erfurt.gbv.de/servlets/DozBibEntryServlet?mode=show&id=ube_mods_00001138 (045R)

PPN:178696886X
https://thunibib-erfurt.gbv.de/servlets/DozBibEntryServlet?mode=show&id=ube_mods_00001160 (044K)

PPN:1844966062
https://thunibib-erfurt.gbv.de/servlets/DozBibEntryServlet?mode=show&id=ube_mods_00001176 (044N)

**Comment by rsteph-de** [comment]
Kannst Du bitte die Pica-PPNs der MyCoRe-MODS-Dokumente ergänzen. Ich habe auf die thunibib keinen Zugriff.

**Comment by rsteph-de** [comment]
Können wir die Quelle des Schlagwortes (PicaFeld) für uns irgendwie im MODS kenntlich machen?
Damit bleibt das Mapping nachvollziehbar und man kann ggf. nach der XSLT-Transformation nochmal im Postprocessing aufräumen.
An irgendeiner Steller machen wir das  auch schon, glaube ich.

**Comment by Possommi** [comment]
> Können wir die Quelle des Schlagwortes (PicaFeld) für uns irgendwie im MODS kenntlich machen? Damit bleibt das Mapping nachvollziehbar und man kann ggf. nach der XSLT-Transformation nochmal im Postprocessing aufräumen. An irgendeiner Steller machen wir das auch schon, glaube ich.

 <mods:subject authority="k10plus_field_555X"> wird an anderer Stelle gesetzt, ich würde das analog machen.

**Comment by rsteph-de** [comment]
Wollen wir bei der RVK gleich "All-In" gehen:
``` xml
<!--RVK (neu, Idee) -->
<mods:subject authority="k10plus_field_5090">
  <mods:topic authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/ST%20300%20-%20ST%20308"
              authority="rvk" value="ST 300 - ST 308">Künstliche Intelligenz</mods:topic>
</mods:subject>
<!--GND (IST-Stand)-->
<mods:subject authority="k10plus_field_555X">
  <mods:topic authorityURI="http://d-nb.info/gnd/"
              valueURI="http://d-nb.info/gnd/4129772-6"
              authority="gnd">Biowissenschaften</mods:topic>
</mods:subject>
```
Das erfordert dann vermutlich einen zusätzlichen Abruf mit der PPN des Normdatensatzes

**Comment by rsteph-de** [comment]
Theoretisch müssen wir auch den Baum aufsammeln, weil die Notation ohne Kontext wenig aussagt.
Beispiel : https://unapi.k10plus.de/?&format=picaxml&id=k10plus:ppn:1270781723
in MODS:
``` xml
<!--RVK (neu, Idee) -->
<mods:subject authority="k10plus_field_5090">
  <!-- nur "echtes" Topic mit usage und authorityURI und valueURI -->
  <mods:topic usage="primary" authority="rvk" value="DI 3000"
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI%203000">
              Allgemeines Deutschland</mods:topic>
  <mods:topic authority="rvk" value="D"></mods:topic>
              Pädagogik</mods:topic>
  <mods:topic authority="rvk" value="DI"></mods:topic>
              Bildungspolitik, Kulturpolitik</mods:topic>
              <!--Achtung: Leerzeichen vor und nach Bindestrich in RVK ja, im GBV Normdatensatz nicht? -->
  <mods:topic authority="rvk" value="DI 3000 - DI3009"></mods:topic>
              Bildungsplanung</mods:topic>
</mods:subject>
```

**Comment by rsteph-de** [comment]
Sebastian schlägt im Kontext von mods:geographic vor, nur die Attribute authority und valueURI zu verwenden und auf die authorityURI zu verzichten.

**Comment by kkrebs** [comment]
> 

Ich würde an dieser Stelle erstmal dabei bleiben authorityURI und valueURI aufzuschreiben. Das sollten wir separat angehen.

**Comment by kkrebs** [comment]
```xml
<mods:subject authority="k10plus_field_5090" valueURI="https://uri.gbv.de/document/gvk:ppn:1270781723">
  <!-- "echtes" Topic mit usage-->
  <mods:topic usage="primary" authority="rvk""
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI%203000">
              Allgemeines Deutschland</mods:topic>
</mods:subject>
```

**Comment by Possommi** [comment]
> Wir haben uns darauf geeinigt nur den eigentlichen Eintrag ohne den kompletten Baum zu übernehmen. Dieser kann dann anhand der PPN über die unapi nachgeholt werden. Dazu muss aber noch die PPN gespeichert werden. Da bei der RVK keine Schlagwortketten abgelegt werden, können wir die PPN gefahrlos als valueURI im mods:subject abspeichern. So dass der Eintrag dann wie folgt aussieht:
> 
> ```
> <mods:subject authority="k10plus_field_5090" valueURI="https://uri.gbv.de/document/gvk:ppn:1270781723">
>   <mods:topic usage="primary" authority="rvk"
>               authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
>               valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI%203000">
>               Allgemeines Deutschland</mods:topic>
> </mods:subject>
> ```

@kkrebs @rsteph-de 

@usage is kein erlaubtes Attribut an mods:topic

**Comment by Possommi** [comment]
> ah, @Usage kann dann da auch und sowieso raus. Das wäre eh nur relevant gewesen um das eigentliche Schlagwort zu markieren. Ist ja aber mit der jetztigen Lösung nicht mehr nötig.

wenn wir jetzt den Import machen würden (ohne Hierarchie) dann hätten wir in der thunibin dreimal das Schlagwort: "Allgemeines und Deutschland" im Ergebnis :(

**Comment by rsteph-de** [comment]
Das spräche dann doch wieder dafür, die Hierarchie direkt ins MODS zu übernehmen.
Die Wiederholung von mods:topic ist aber ungünstig, weil das eher für Schlagwortketten (mehre Schlagwörter in Kombination) als für hierarchische Gliederungen verwendet wird.
Das alles verkettet als Text in mods:topic zu tun ist mir aber auch zu "platt":
```xml
<mods:topic>
Pädagogik / Spezialfragen des gesamten Schulsystems / Schulleistung und Leistungsschule; Leistungstest / Allgemeines und Deutschland
</mods:topic>
```
Es wäre schön "für später" auch die IDs der oberen Kategorien zu haben und den tatsächlichen Begriff "Allgemeines und Deutschland" hervorzuheben.

**Comment by Possommi** [comment]
> Das spräche dann doch wieder dafür, die Hierarchie direkt ins MODS zu übernehmen. Die Wiederholung von mods:topic ist aber ungünstig, weil das eher für Schlagwortketten (mehre Schlagwörter in Kombination) als für hierarchische Gliederungen verwendet wird. Das alles verkettet als Text in mods:topic zu tun ist mir aber auch zu "platt":
> 
> ```
> <mods:topic>
> Pädagogik / Spezialfragen des gesamten Schulsystems / Schulleistung und Leistungsschule; Leistungstest / Allgemeines und Deutschland
> </mods:topic>
> ```
> 
> Es wäre schön "für später" auch die IDs der oberen Kategorien zu haben und den tatsächlichen Begriff "Allgemeines und Deutschland" hervorzuheben.

Ich kann gut leben mit einzelnen mods:topic innerhalb eines mods:subject. Können in 045R Schlagwortketten vorkommen? Wenn nicht kann man ja über die authoritiy Fallunterscheidungen machen.

**Comment by rsteph-de** [comment]
Schlagwortketten sollte es in der RVK-Notation nicht geben.

Die Idee, das eigentliche Schlagwort über die authority zu kennzeichnen, finde ich gut.
Nur das "echte" Topic bekommt das `authority` Attribut (und ist implizit auch immer das 1. mods:topic).
Zusätzlich würde ich noch die Hiearchie-Reihenfolge der weiteren Topics umdrehen.
Dann geht es konsequent vom Speziellen zum Allgemeinen.
``` xml
<!--RVK (überarbeitet) -->
<mods:subject authority="k10plus_field_5090">
  <!-- "echtes" Topic mit usage-->
  <mods:topic authority="rvk"
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI%203000">
              Allgemeines Deutschland</mods:genre>
  <mods:topic
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI 3000%20-%20DI3009">
              Bildungsplanung</mods:topic>
  <mods:topic
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI">
              Bildungspolitik, Kulturpolitik</mods:topic>
              <!--Achtung: Leerzeichen vor und nach Bindestrich in RVK ja, im GBV Normdatensatz nicht? -->
  <mods:topic
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/D">
              Pädagogik</mods:topic>
</mods:subject>
```

**Comment by kkrebs** [comment]
Wenn man das "echte" Topic herausfinden und kennzeichnen kann, kann man auch unserem ursprünglichen Plan folgen und nur dieses übernehmen. Ich bin nach wie vor dafür nicht alle topics zu übernehmen, weil wir so Schlagwortketten abbilden! Ich hätte das mods gern an dieser Stelle klar und einheitlich!

**Comment by rsteph-de** [comment]
Das bedeutet dann, dass wir (so wie der Katalog) auch nur die Notation anzeigen:
Alle weiteren Infos Hierarchie + Bezeichner per Javascript + UnAPI-Abfrage generierter Infobox:
![grafik](https://github.com/MyCoRe-Org/pica2mods/assets/20067327/60b399d8-0c6c-47fc-8cad-9c051fca7a2a)

**Comment by rsteph-de** [comment]
Ergebnis:
``` xml
<mods:subject authority="k10plus_field_5090" valueURI="https://uri.gbv.de/document/gvk:ppn:1270781723">
  <mods:topic usage="primary" authority="rvk"
              authorityURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online"
              valueURI="https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/DI%203000">
              DI 3000</mods:topic>
</mods:subject>
```

**Comment by kkrebs** [comment]
Genau!
