### ISSUE TITLE
Angabe bei mehrtägiger Konferenzdauer

### ISSUE THREAD

**Issue by Possommi** [MyCoRe-Org/pica2mods#69]
Mir ist aufgefallen, dass die Angabe bei mehrtägigen Konferenzen noch nicht korrekt funktioniert.
Im Bibliothekssystem steht folgende Konferenzangabe im betreffenden PICA+ Feld:
030F *ƒa*Conference "Antiquity in Global Perspective: Concepts of the Past and Constructions of Collective Identities"*ƒk*Bern*ƒp*2010.10.27-30
In der ThUniBib wird nur das Datum 27.10.2010 ausgegeben.
[PPN: 1615859837](https://unapi.k10plus.de/?&format=picaxml&id=opac-de-3204:ppn:1615859837)

**Comment by rsteph-de** [comment]
Vielleicht sollten wir dann gleich alle anderen Fälle mit implementieren.
siehe: https://format.k10plus.de/k10plushelp.pl?cmd=kat&val=3160&katalog=Standard#$d
Nur die Fälle, die auf Monat enden, würde ich ggf. erstmal unverändert übernehmen ( Jahr.Monat. /Jahr.Monat.-Jahr.Monat. / Jahr.Monat.-Monat.) - Oder Du findest eine halbwegs normierte Notation
Die RegExe könnten mit ^ und $ für Anfang und Ende einer Zeichenkette robuster gemacht werden.
Berücksichtige dabei den Punkt am Ende von unvollständigen Angaben (Jahr. / Jahr.Monat.). Den würde ich im RegEx optional machen (wer weiß, ob sich alle Katalogisier daran gehalten habe ;-) )
