### ISSUE TITLE
FSU040THUL-2452 037C Pica+ Feld übernehmen

### ISSUE THREAD

**Issue by Possommi** [MyCoRe-Org/pica2mods#89]
PPN [641146515](https://lab.ub.uni-rostock.de/pica2mods/?catalog=erf&ppn=641146515)

Kommentar einer Kundin:

> [...]
> Hintergrund unserer Frage ist, dass es u.U. Hochschulschriften mit abweichendem Erscheinung- und Hochschulschriftenjahr gibt. Außerdem kann die Anzeige von älteren Datensätzen unterschiedlich zu neueren Datensätzen sein.
> [...]
> Unabhängig davon ist diese Information aus unserer Sicht relevant und sollte importiert werden. 
> [...]

**Comment by rsteph-de** [comment]
Bei uns und in dem Beispiel oben steht in dem Feld in Unterfeld `$a` immer der komplette **Hochschulschriftenvermerk**:
[PPN 844427985](https://unapi.k10plus.de/?&format=picaxml&id=gvk:ppn:844427985): 
` 037C$a: Rostock, Univ., Mathematisch-Naturwiss. Fak., Diss., 2015 `
Das würde ich dann eher in einer mods:note sehen.
Vorschlag  (von Deepl, verhandelbar) für note/@type: 'university_thesis_note' 

Das betrifft aber vor allem Alt-Daten. Aktuell katalogisieren wir weitere Unterfelder:
z.B. [PPN 1880233193](https://lab.ub.uni-rostock.de/pica2mods/?catalog=gvk&ppn=1880233193)
`037C | $dDissertation$eUniversität Rostock$f2023$gKumulative Dissertation `
Diese Informationen können in der Tat sinnvoll sein, habe aber spontan keine Idee, wie wir die "sinnvoll" gefeldert ins MODS bekommen.

Das Jahr aus `037C$f landet bei uns schon im
```
<mods:originInfo eventType="publication">
      <mods:dateOther type="defence" encoding="w3cdtf">2023</mods:dateOther>
</mods:originInfo>
````
Die Angaben in den Altdaten ($a) sollten relativ standardisiert erfasst worden sein und das Jahr vermutlich immer am Ende des Strings stehen. Das müsste man mal evaluieren und dann könnte man ggf. per Heuristik (Regex '4stellige Zahl' / Substring) auch das Jahr aus $a hier eintragen.
